apiVersion: v1
kind: Service
metadata:
  labels:
    app: movieapp-service
  name: movieapp-service
spec:
  ports:
  - name: movieapp-port
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: movieapp
  type: LoadBalancer
status:
  loadBalancer: {}
